name: AkatroxTempBlocks
version: 1.0
main: org.akatrox.AkatroxTempBlocks
api-version: '1.16'
author: benakatrox
commands:
  atb:
    description: Config dosyasını yeniden yükler.
    usage: /<command> reload
    permission: atb.reload
permissions:
  atb.reload:
    description: Plugin config dosyasını yeniden yükleme izni verir.
    default: true
